## Import necessary modules

In [80]:
import time
t0 = time.clock()
import pandas as pd
from pandas.tseries.offsets import BDay
import numpy as np
import datetime as dt
from copy import copy
import warnings
import matplotlib.pyplot as plt
%matplotlib inline

## datetime management

In [81]:
d = dt.date.today()
# ---------- Days ---------- 
l10 = d - 10 * BDay()
l21 = d - 21 * BDay()
l63 = d - 63 * BDay()
l252 = d - 252 * BDay()
# ---------- Years ---------- 
l252_x2 = d - 252 * 2 * BDay() 
l252_x3 = d - 252 * 3 * BDay() 
l252_x5 = d - 252 * 5 * BDay()
l252_x7 = d - 252 * 7 * BDay() 
l252_x10 = d - 252 * 10 * BDay() 
l252_x20 = d - 252 * 20 * BDay() 
l252_x25 = d - 252 * 25 * BDay()

## Filepath management

In [82]:
project_dir = r'/Users/hudson/Code/marketModel/'
price_path = project_dir + r'stock_price_data/'

## "BarChart" api access

In [83]:
apikey = 'a207db3b2e61eac30ed9b9cd18b2e0d0'


def construct_barChart_url(sym, start_date, freq, api_key=apikey):
    '''Function to construct barchart api url
    Get the barChart url for
    * sym -- the ticker symbol
    * start_date -- the earliest time in format yyyymmddhhmmss
    * freq -- ['days', 'hours', 'minutes', 'seconds']
    * api_key the barChart api key
    '''
    url = 'http://marketdata.websol.barchart.com/getHistory.csv?' +\
            'key={}&symbol={}&type={}&startDate={}'\
    .format(api_key, sym, freq, start_date)

    return url

In [84]:
api_test_url = construct_barChart_url('GOOG', '20170829093000', 'minutes', apikey)
goog = pd.read_csv(api_test_url, parse_dates=['timestamp'])

In [85]:
goog

,symbol,timestamp,tradingDay,open,high,low,close,volume
0,GOOG,2017-08-29 13:30:00,2017-08-29,905.1000,906.4800,905.0000,905.0000,26316
1,GOOG,2017-08-29 13:31:00,2017-08-29,905.4866,906.6149,905.2501,906.6149,2377
2,GOOG,2017-08-29 13:32:00,2017-08-29,906.7809,908.1400,906.7100,908.1400,3523
3,GOOG,2017-08-29 13:33:00,2017-08-29,908.0200,908.1400,907.4100,907.8272,3850
4,GOOG,2017-08-29 13:34:00,2017-08-29,907.9900,908.8700,907.8300,908.8700,2964
5,GOOG,2017-08-29 13:35:00,2017-08-29,908.8600,908.9500,908.3300,908.4750,3400
6,GOOG,2017-08-29 13:36:00,2017-08-29,908.4100,909.1300,908.3300,909.0700,4100
7,GOOG,2017-08-29 13:37:00,2017-08-29,909.2200,910.0400,909.1100,910.0400,9242
8,GOOG,2017-08-29 13:38:00,2017-08-29,909.5550,909.5550,909.3500,909.3700,400
9,GOOG,2017-08-29 13:39:00,2017-08-29,909.3200,909.6300,909.2100,909.2300,2050
10,GOOG,2017-08-29 13:40:00,2017-08-29,909.2000,909.3136,908.9242,909.2200,1800
11,GOOG,2017-08-29 13:41:00,2017-08-29,909.3100,909.3100,908.3060,908.3600,600
12,GOOG,2017-08-29 13:42:00,2017-08-29,908.3400,908.3500,907.8900,908.0100,1866
13,GOOG,2017-08-29 13:43:00,2017-08-29,908.0325,908.6600,907.7400,907.7400,1500
14,GOOG,2017-08-29 13:44:00,2017-08-29,907.5100,908.1000,907.0001,907.5000,6387
15,GOOG,2017-08-29 13:45:00,2017-08-29,907.8900,908.2400,907.8143,908.0662,447
16,GOOG,2017-08-29 13:46:00,2017-08-29,908.2100,909.7700,908.2100,909.2500,3150
17,GOOG,2017-08-29 13:47:00,2017-08-29,908.9870,909.2650,908.9300,909.2450,1335
18,GOOG,2017-08-29 13:48:00,2017-08-29,909.0700,909.6100,908.8000,909.6100,2790
19,GOOG,2017-08-29 13:49:00,2017-08-29,910.0075,910.4000,909.7600,910.1900,2600
20,GOOG,2017-08-29 13:50:00,2017-08-29,910.1749,910.6500,910.0300,910.6500,2463
21,GOOG,2017-08-29 13:51:00,2017-08-29,910.6600,911.0700,910.5025,910.8300,1844
22,GOOG,2017-08-29 13:52:00,2017-08-29,910.6638,910.8199,910.0000,910.2500,3100
23,GOOG,2017-08-29 13:53:00,2017-08-29,910.0775,910.1100,909.5129,909.5600,1969
24,GOOG,2017-08-29 13:54:00,2017-08-29,909.2700,909.9249,909.2700,909.9207,2396
25,GOOG,2017-08-29 13:55:00,2017-08-29,910.0000,910.3650,909.9250,910.3300,1000
26,GOOG,2017-08-29 13:56:00,2017-08-29,910.3100,910.9600,910.2500,910.2500,1305
27,GOOG,2017-08-29 13:57:00,2017-08-29,910.1700,910.1700,909.4100,909.4100,600
28,GOOG,2017-08-29 13:58:00,2017-08-29,909.4750,910.4475,909.4750,910.4475,2891
29,GOOG,2017-08-29 13:59:00,2017-08-29,910.4800,911.3000,910.4800,910.8200,2800
...,...,...,...,...,...,...,...,...
1494,GOOG,2017-09-01 19:31:00,2017-09-01,938.1200,938.1300,937.8300,937.8300,2800
1495,GOOG,2017-09-01 19:32:00,2017-09-01,937.8800,938.1500,937.8800,938.1200,2900
1496,GOOG,2017-09-01 19:33:00,2017-09-01,938.1050,938.3300,938.0600,938.0700,3427
1497,GOOG,2017-09-01 19:34:00,2017-09-01,938.0510,938.1500,937.8500,937.9500,2198
1498,GOOG,2017-09-01 19:35:00,2017-09-01,937.8100,937.9000,937.7300,937.8900,2043
1499,GOOG,2017-09-01 19:36:00,2017-09-01,937.9900,937.9900,937.8000,937.8500,1400
1500,GOOG,2017-09-01 19:37:00,2017-09-01,937.7488,937.8600,937.5000,937.8200,3323
1501,GOOG,2017-09-01 19:38:00,2017-09-01,937.8300,937.8300,937.6500,937.6600,1000
1502,GOOG,2017-09-01 19:39:00,2017-09-01,937.7250,937.8300,937.5300,937.5300,8246
1503,GOOG,2017-09-01 19:40:00,2017-09-01,937.5100,937.7000,937.4700,937.5250,1880
1504,GOOG,2017-09-01 19:41:00,2017-09-01,937.5650,937.6000,937.3400,937.3900,1189
1505,GOOG,2017-09-01 19:42:00,2017-09-01,937.4200,937.4400,937.3000,937.4400,700
1506,GOOG,2017-09-01 19:43:00,2017-09-01,937.3700,937.4800,937.2800,937.4800,949
1507,GOOG,2017-09-01 19:44:00,2017-09-01,937.6500,937.7500,937.5000,937.5000,1284
1508,GOOG,2017-09-01 19:45:00,2017-09-01,937.4310,937.5800,937.4200,937.5700,900
1509,GOOG,2017-09-01 19:46:00,2017-09-01,937.5500,937.6067,937.4400,937.4400,2000
1510,GOOG,2017-09-01 19:47:00,2017-09-01,937.4300,937.4300,937.2050,937.3050,2051
1511,GOOG,2017-09-01 19:48:00,2017-09-01,937.3600,937.4100,937.1100,937.1100,2881
1512,GOOG,2017-09-01 19:49:00,2017-09-01,937.1100,937.1992,937.1100,937.1200,1005
1513,GOOG,2017-09-01 19:50:00,2017-09-01,937.1600,937.7500,937.1600,937.5950,1900
1514,GOOG,2017-09-01 19:51:00,2017-09-01,937.6700,937.6700,937.2050,937.4650,3500
1515,GOOG,2017-09-01 19:52:00,2017-09-01,937.6300,937.8600,937.5650,937.5650,3455
1516,GOOG,2017-09-01 19:53:00,2017-09-01,937.6900,937.7600,937.4400,937.5000,4200
1517,GOOG,2017-09-01 19:54:00,2017-09-01,937.6000,937.7200,937.5400,937.5400,1500
1518,GOOG,2017-09-01 19:55:00,2017-09-01,937.7500,937.9450,937.6300,937.7100,5100
1519,GOOG,2017-09-01 19:56:00,2017-09-01,937.7200,937.7550,937.5900,937.5900,2005
1520,GOOG,2017-09-01 19:57:00,2017-09-01,937.6600,937.7450,937.5600,937.5700,2500
1521,GOOG,2017-09-01 19:58:00,2017-09-01,937.6100,937.6566,937.3050,937.3200,5320
1522,GOOG,2017-09-01 19:59:00,2017-09-01,937.3600,937.4800,937.0000,937.0000,9655
1523,GOOG,2017-09-01 20:00:00,2017-09-01,937.3400,937.3400,937.3400,937.3400,44240

## Now start pulling in data for our sample stock symbols

In [86]:
symbols = pd.read_csv('/Users/hudson/Code/marketModel/stock_data/symbols.csv')

In [114]:
# Pull data for all the test symbols
start_time = '20170704000000'
prices = {}

for symbol in symbols.ticker_symbol:
    # Construct the appropriate URL
    url = construct_barChart_url(symbol, start_time, 'minutes', apikey)
    
    try:
        # Read the data from the url
        data = pd.read_csv(url, parse_dates=['timestamp']).set_index('timestamp')

        # Drop the symbol and trading day columns
        data = data.drop(['symbol','tradingDay'], axis=1)

        # Convert the times to eastern time zone
        data.index = data.index.tz_localize('utc').tz_convert('US/Eastern')

        # Add data to prices dictionary
        prices[symbol] = data
    except:
        print "Failed to load data for " + symbol
        continue

In [115]:
# Concatenate all of the stock data into a multiIndex dataframe
stock_data = pd.concat(prices.values(), keys=prices.keys())
stock_data.index.set_names(['ticker', 'timestamp'], inplace=True)
stock_data

                                    open    high     low   close  volume
ticker timestamp
ASTC   2017-07-05 09:30:00-04:00  0.9120  0.9120  0.9120  0.9120     112
       2017-07-05 09:51:00-04:00  0.9150  0.9150  0.9000  0.9000    1900
       2017-07-05 11:10:00-04:00  0.9200  0.9200  0.9200  0.9200     100
       2017-07-05 11:29:00-04:00  0.9131  0.9131  0.9131  0.9131     670
       2017-07-05 12:08:00-04:00  0.9296  0.9296  0.9296  0.9296     500
       2017-07-05 12:47:00-04:00  0.9280  0.9280  0.9280  0.9280    1180
       2017-07-05 13:11:00-04:00  0.9027  0.9296  0.9027  0.9118    6500
       2017-07-05 13:12:00-04:00  0.9100  0.9100  0.9100  0.9100     100
       2017-07-05 13:19:00-04:00  0.8800  0.8800  0.8618  0.8618    1000
       2017-07-05 13:25:00-04:00  0.8600  0.8600  0.8600  0.8600     618
       2017-07-05 13:27:00-04:00  0.8800  0.8800  0.8800  0.8800    3531
       2017-07-05 13:56:00-04:00  0.8600  0.8600  0.8600  0.8600   10000
       2017-07-05 13:57:00-04:00  0.8601  0.8601  0.8600  0.8600   10000
       2017-07-05 14:06:00-04:00  0.9000  0.9000  0.9000  0.9000     100
       2017-07-05 14:24:00-04:00  0.9000  0.9000  0.9000  0.9000    8700
       2017-07-05 14:27:00-04:00  0.9197  0.9197  0.9197  0.9197     200
       2017-07-05 15:12:00-04:00  0.9200  0.9200  0.9200  0.9200     100
       2017-07-05 15:51:00-04:00  0.9200  0.9200  0.9200  0.9200     100
       2017-07-06 09:30:00-04:00  0.8800  0.8800  0.8800  0.8800    1151
       2017-07-06 09:51:00-04:00  0.8801  0.8801  0.8801  0.8801     100
       2017-07-06 09:56:00-04:00  0.8800  0.8800  0.8800  0.8800     100
       2017-07-06 10:22:00-04:00  0.9073  0.9073  0.9073  0.9073     222
       2017-07-06 10:35:00-04:00  0.9100  0.9100  0.8800  0.8805    2500
       2017-07-06 10:45:00-04:00  0.9246  0.9246  0.9246  0.9246     700
       2017-07-06 10:51:00-04:00  0.9000  0.9000  0.9000  0.9000    1000
       2017-07-06 10:52:00-04:00  0.9000  0.9000  0.9000  0.9000    9000
       2017-07-06 11:00:00-04:00  0.8895  0.8895  0.8895  0.8895     500
       2017-07-06 11:08:00-04:00  0.9000  0.9000  0.9000  0.9000     200
       2017-07-06 11:16:00-04:00  0.9000  0.9000  0.8997  0.9000     700
       2017-07-06 12:25:00-04:00  0.9103  0.9103  0.9103  0.9103    1400
...                                  ...     ...     ...     ...     ...
MOC    2017-08-31 10:51:00-04:00  2.9800  2.9800  2.9800  2.9800     100
       2017-08-31 10:57:00-04:00  2.8900  2.9200  2.8900  2.9200    3000
       2017-08-31 11:24:00-04:00  2.9900  3.0300  2.9900  3.0300    1907
       2017-08-31 11:36:00-04:00  3.0216  3.0216  3.0216  3.0216     890
       2017-08-31 11:41:00-04:00  3.0300  3.0300  3.0100  3.0300     300
       2017-08-31 12:39:00-04:00  2.9850  2.9854  2.9850  2.9854    1900
       2017-08-31 12:40:00-04:00  2.9900  2.9900  2.9900  2.9900     100
       2017-08-31 13:05:00-04:00  2.9500  2.9900  2.9500  2.9900     200
       2017-08-31 14:46:00-04:00  2.9000  2.9000  2.9000  2.9000     300
       2017-08-31 15:03:00-04:00  2.9200  2.9200  2.9200  2.9200     300
       2017-08-31 15:12:00-04:00  2.9500  2.9500  2.9500  2.9500     100
       2017-08-31 15:45:00-04:00  2.9500  2.9500  2.9499  2.9500    2332
       2017-08-31 15:59:00-04:00  3.0200  3.0200  3.0200  3.0200     200
       2017-08-31 16:00:00-04:00  2.9000  2.9000  2.9000  2.9000     498
       2017-09-01 10:05:00-04:00  3.0200  3.0200  3.0200  3.0200     100
       2017-09-01 11:01:00-04:00  2.9600  2.9600  2.9600  2.9600     100
       2017-09-01 11:07:00-04:00  2.9700  2.9700  2.9700  2.9700     100
       2017-09-01 12:49:00-04:00  2.9700  2.9700  2.9500  2.9500     400
       2017-09-01 13:04:00-04:00  2.9200  2.9200  2.9200  2.9200     100
       2017-09-01 13:06:00-04:00  2.9481  2.9481  2.9481  2.9481     500
       2017-09-01 13:41:00-04:00  2.9200  2.9200  2.8700  2.8700    2100
       2017-09-01 13:42:00-04:00  2.9100  2.9400  2.8800  2.9011    5100
       2017-09-01 13:43:00-04:00  2.9300  2.9700  2.9300  2.9600    3951
       2017-09-01 14:20:00-04:00  2.9632  2.9632  2.9632  2.9632     494
       2017-09-01 15:17:00-04:00  2.9600  2.9600  2.9600  2.9600     200
       2017-09-01 15:19:00-04:00  2.9600  2.9600  2.9600  2.9600     359
       2017-09-01 15:20:00-04:00  2.9600  2.9600  2.9600  2.9600     100
       2017-09-01 15:37:00-04:00  3.0000  3.0200  3.0000  3.0200    5402
       2017-09-01 15:38:00-04:00  3.0000  3.0000  3.0000  3.0000    8301
       2017-09-01 15:45:00-04:00  3.0200  3.0200  2.9900  2.9900     200

[36134 rows x 5 columns]

## Write to hdf

In [116]:
stock_data.to_hdf(project_dir + 'stock_data/' + 'stock_data.hdf', 'table')

## Play with the multi-index data

In [117]:
stock_data.index.names

FrozenList([u'ticker', u'timestamp'])

In [118]:
print stock_data.index.levels[0], min(stock_data.index.levels[1]), max(stock_data.index.levels[1])

Index([u'ASTC', u'PAVM', u'CODA', u'WSTL', u'MICR', u'SEAC', u'GBR', u'CPST',
       u'CYAN', u'ATLC', u'WTT', u'LRAD', u'DTRM', u'AVIR', u'UTSI', u'JCS',
       u'ZDGE', u'REFR', u'FORD', u'APHB', u'JVA', u'VSR', u'BNSO', u'ARDM',
       u'LEU', u'MOC'],
      dtype='object', name=u'ticker') 2017-07-05 09:30:00-04:00 2017-09-01 16:00:00-04:00